# Generated by Django 4.0.2 on 2022-02-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='request',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialize',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialize',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.clinic'),
            preserve_default=False,
        ),
    ]
