# Generated by Django 4.0.2 on 2022-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_appointment_clinic_remove_request_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
