# Generated by Django 4.0.2 on 2022-02-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_day_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='num',
        ),
    ]
