# Generated by Django 4.0.2 on 2022-02-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_day_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
