# Generated by Django 4.0.2 on 2022-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_doctor_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='missed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='wating', max_length=100),
        ),
    ]
