# Generated by Django 4.0.2 on 2022-02-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_appointment_doctor_alter_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='approved',
        ),
    ]
